// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// count_k_cycle
arma::vec count_k_cycle(const arma::mat& A, const int& max_cycle_order);
RcppExport SEXP _nethist_count_k_cycle(SEXP ASEXP, SEXP max_cycle_orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const int& >::type max_cycle_order(max_cycle_orderSEXP);
    rcpp_result_gen = Rcpp::wrap(count_k_cycle(A, max_cycle_order));
    return rcpp_result_gen;
END_RCPP
}
// multinethist_fastgreedy
List multinethist_fastgreedy(const arma::icube& A, const int& hbar, const arma::uvec& inputLabelVec, const int& max_itr, const int& swap_rule, const int& consecutive_iter_threshold, const bool& verbose);
RcppExport SEXP _nethist_multinethist_fastgreedy(SEXP ASEXP, SEXP hbarSEXP, SEXP inputLabelVecSEXP, SEXP max_itrSEXP, SEXP swap_ruleSEXP, SEXP consecutive_iter_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::icube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const int& >::type hbar(hbarSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type inputLabelVec(inputLabelVecSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_itr(max_itrSEXP);
    Rcpp::traits::input_parameter< const int& >::type swap_rule(swap_ruleSEXP);
    Rcpp::traits::input_parameter< const int& >::type consecutive_iter_threshold(consecutive_iter_thresholdSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(multinethist_fastgreedy(A, hbar, inputLabelVec, max_itr, swap_rule, consecutive_iter_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// mnhistCommon_fastgreedy
List mnhistCommon_fastgreedy(const arma::icube& A, const int& hbar, const arma::uvec& inputLabelVec, const int& max_itr, const int& swap_rule, const int& consecutive_iter_threshold, const bool& verbose);
RcppExport SEXP _nethist_mnhistCommon_fastgreedy(SEXP ASEXP, SEXP hbarSEXP, SEXP inputLabelVecSEXP, SEXP max_itrSEXP, SEXP swap_ruleSEXP, SEXP consecutive_iter_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::icube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const int& >::type hbar(hbarSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type inputLabelVec(inputLabelVecSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_itr(max_itrSEXP);
    Rcpp::traits::input_parameter< const int& >::type swap_rule(swap_ruleSEXP);
    Rcpp::traits::input_parameter< const int& >::type consecutive_iter_threshold(consecutive_iter_thresholdSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(mnhistCommon_fastgreedy(A, hbar, inputLabelVec, max_itr, swap_rule, consecutive_iter_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// net_summary_subsample_adj
arma::mat net_summary_subsample_adj(const arma::mat& A, const arma::vec& subsample_sizes, int max_cycle_order, int R);
RcppExport SEXP _nethist_net_summary_subsample_adj(SEXP ASEXP, SEXP subsample_sizesSEXP, SEXP max_cycle_orderSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type subsample_sizes(subsample_sizesSEXP);
    Rcpp::traits::input_parameter< int >::type max_cycle_order(max_cycle_orderSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(net_summary_subsample_adj(A, subsample_sizes, max_cycle_order, R));
    return rcpp_result_gen;
END_RCPP
}
// nethist_fastgreedy
List nethist_fastgreedy(const arma::imat& A, const int& hbar, const arma::uvec& inputLabelVec, const int& max_itr, const int& swap_rule, const int& consecutive_iter_threshold, const bool& verbose);
RcppExport SEXP _nethist_nethist_fastgreedy(SEXP ASEXP, SEXP hbarSEXP, SEXP inputLabelVecSEXP, SEXP max_itrSEXP, SEXP swap_ruleSEXP, SEXP consecutive_iter_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const int& >::type hbar(hbarSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type inputLabelVec(inputLabelVecSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_itr(max_itrSEXP);
    Rcpp::traits::input_parameter< const int& >::type swap_rule(swap_ruleSEXP);
    Rcpp::traits::input_parameter< const int& >::type consecutive_iter_threshold(consecutive_iter_thresholdSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(nethist_fastgreedy(A, hbar, inputLabelVec, max_itr, swap_rule, consecutive_iter_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// ffct
double ffct(int n, int k);
RcppExport SEXP _nethist_ffct(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(ffct(n, k));
    return rcpp_result_gen;
END_RCPP
}
// hamming_dist_adj_mat
arma::mat hamming_dist_adj_mat(const arma::imat& A);
RcppExport SEXP _nethist_hamming_dist_adj_mat(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(hamming_dist_adj_mat(A));
    return rcpp_result_gen;
END_RCPP
}
// is_undirected_simple
bool is_undirected_simple(const arma::mat& A);
RcppExport SEXP _nethist_is_undirected_simple(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(is_undirected_simple(A));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_nethist_count_k_cycle", (DL_FUNC) &_nethist_count_k_cycle, 2},
    {"_nethist_multinethist_fastgreedy", (DL_FUNC) &_nethist_multinethist_fastgreedy, 7},
    {"_nethist_mnhistCommon_fastgreedy", (DL_FUNC) &_nethist_mnhistCommon_fastgreedy, 7},
    {"_nethist_net_summary_subsample_adj", (DL_FUNC) &_nethist_net_summary_subsample_adj, 4},
    {"_nethist_nethist_fastgreedy", (DL_FUNC) &_nethist_nethist_fastgreedy, 7},
    {"_nethist_ffct", (DL_FUNC) &_nethist_ffct, 2},
    {"_nethist_hamming_dist_adj_mat", (DL_FUNC) &_nethist_hamming_dist_adj_mat, 1},
    {"_nethist_is_undirected_simple", (DL_FUNC) &_nethist_is_undirected_simple, 1},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_nethist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
