# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.graphest_fastgreedy <- function(A, hbar, inputLabelVec, verbose) {
    .Call(`_nethist_graphest_fastgreedy`, A, hbar, inputLabelVec, verbose)
}

