# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.count_k_cycle <- function(A, max_cycle_order) {
    .Call(`_nethist_count_k_cycle`, A, max_cycle_order)
}

.multinethist_fastgreedy <- function(A, hbar, inputLabelVec, max_itr, swap_rule, consecutive_iter_threshold, verbose) {
    .Call(`_nethist_multinethist_fastgreedy`, A, hbar, inputLabelVec, max_itr, swap_rule, consecutive_iter_threshold, verbose)
}

.mnhistCommon_fastgreedy <- function(A, hbar, inputLabelVec, max_itr, swap_rule, consecutive_iter_threshold, verbose) {
    .Call(`_nethist_mnhistCommon_fastgreedy`, A, hbar, inputLabelVec, max_itr, swap_rule, consecutive_iter_threshold, verbose)
}

.multinethist_sa <- function(A, hbar, inputLabelVec, max_itr, alpha, T_min, swap_rule, verbose) {
    .Call(`_nethist_multinethist_sa`, A, hbar, inputLabelVec, max_itr, alpha, T_min, swap_rule, verbose)
}

.mnhistCommon_sa <- function(A, hbar, inputLabelVec, max_itr, alpha, T_min, swap_rule, verbose) {
    .Call(`_nethist_mnhistCommon_sa`, A, hbar, inputLabelVec, max_itr, alpha, T_min, swap_rule, verbose)
}

.net_summary_subsample_adj <- function(A, subsample_sizes, max_cycle_order, R) {
    .Call(`_nethist_net_summary_subsample_adj`, A, subsample_sizes, max_cycle_order, R)
}

.nethist_fastgreedy <- function(A, hbar, inputLabelVec, method, max_itr, swap_rule, consecutive_iter_threshold, verbose) {
    .Call(`_nethist_nethist_fastgreedy`, A, hbar, inputLabelVec, method, max_itr, swap_rule, consecutive_iter_threshold, verbose)
}

.nethist_sa <- function(A, hbar, inputLabelVec, max_itr, alpha, T_min, swap_rule, verbose) {
    .Call(`_nethist_nethist_sa`, A, hbar, inputLabelVec, max_itr, alpha, T_min, swap_rule, verbose)
}

.ffct <- function(n, k) {
    .Call(`_nethist_ffct`, n, k)
}

.hamming_dist_adj_mat <- function(A) {
    .Call(`_nethist_hamming_dist_adj_mat`, A)
}

.is_undirected_simple <- function(A) {
    .Call(`_nethist_is_undirected_simple`, A)
}

