# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.count_k_cycle <- function(A, max_cycle_order) {
    .Call(`_nethist_count_k_cycle`, A, max_cycle_order)
}

.graphest_fastgreedy <- function(A, hbar, bestLabelVec, verbose) {
    .Call(`_nethist_graphest_fastgreedy`, A, hbar, bestLabelVec, verbose)
}

.net_summary_subsample_adj <- function(A, subsample_sizes, max_cycle_order, R) {
    .Call(`_nethist_net_summary_subsample_adj`, A, subsample_sizes, max_cycle_order, R)
}

.ffct <- function(n, k) {
    .Call(`_nethist_ffct`, n, k)
}

.hamming_dist_adj_mat <- function(A) {
    .Call(`_nethist_hamming_dist_adj_mat`, A)
}

.is_undirected_simple <- function(A) {
    .Call(`_nethist_is_undirected_simple`, A)
}

